name: Build

on: 
  push:
    breanches:
      - main
    paths:
      - 'src/**'
      - 'include/**'
      - 'tools/src/**'
      - 'Makefile'
      - '*.mk'
      - '.github/workflows/build.yml'

  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'tools/src/**'
      - 'Makefile'
      - '*.mk'
      - '.github/workflows/build.yml'

jobs:

  build:
    name: Build library

    runs-on: ubuntu-latest
    env:
      CC: gcc
      CFLAGS: -Os -Wall -Wextra -std=c99
    steps:
    - uses: actions/checkout@v4
    
    - name: Build static library
      run: make static
      
    - name: Build shared library
      run: make shared
   
    - name: Compile solsys variants
      run: make solsys
   
    - name: Generate CIO locator data
      run: make cio_file      

      
   
